### ISSUE TITLE
Manual creation of hosts.json required on Windows with VS Code

### ISSUE THREAD

**Issue by abortabort** [wzshiming/gh-gpt#1]
According to the README.md file, the ~\AppData\Local\github-copilot\hosts.json file should be automatically created when logging in to Copilot in an IDE.

However, while using VS Code on Windows, I found that this file wasn't automatically created. I had to manually add it.

**Comment by wzshiming** [comment]
You are right, I tried it in JetBrains, VScode doesn't seem to create it, where did you get the hosts.json?

**Comment by abortabort** [comment]
I manually created the hosts.json file using the following format:
{"github.com":{"user":"<YOUR_USER_NAME>","oauth_token":"ghu_XXXXXXXXXXXXXXX"}}

**Comment by wzshiming** [comment]
Cool, so how did you get the `auth_token`? If there's an easier way to get the `oauth_token`, I think we can get away with not relying on Copilot.

**Comment by wzshiming** [comment]
I added the [login subcommand](https://github.com/wzshiming/gh-gpt?tab=readme-ov-file#login) for without IDE in v0.5.0

That should be enough for your needs
