### ISSUE TITLE
gh-gpt login

### ISSUE THREAD

**Issue by thelege2nd** [wzshiming/gh-gpt#3]
what is this?
gh-gpt login

the instructions is not clear.. i want to run this as a local server.

**Comment by wzshiming** [comment]
the `gh-gpt login` is a way of login.

You'll need to read on

`gh-gpt server --address :8000`

https://github.com/wzshiming/gh-gpt?tab=readme-ov-file#as-a-server

**Comment by thelege2nd** [comment]
![image](https://github.com/wzshiming/gh-gpt/assets/12984941/8340aa33-e48a-4549-b2aa-95c4e23d4196)

do I need the get the GH_COPILOT_TOKEN first? How?  Also, Both commands gh-gpt login and  gh-gpt server --address :8000 does nothing. The command executes successfully but nothing happens, there are no messages or confirmations of any sort.  @wzshiming

**Comment by wzshiming** [comment]
Looks like the login is not working??

```
> go run ./cmd/gh-gpt login
Please take this code "852F-EF00" to authenticate at https://github.com/login/device.
Press 'y' to continue, or any other key to abort.
Waiting for authentication...
ghu_xxxxxxx
> go run ./cmd/gh-gpt run "Hello"
Hello! How can I assist you today?
```

**Comment by wzshiming** [comment]
`gh-gpt login` does not get any response?

**Comment by wzshiming** [comment]
https://github.com/wzshiming/gh-gpt/releases/download/v0.5.0/gh-gpt_windows_amd64.exe

I tested it and it works

**Comment by thelege2nd** [comment]
@wzshiming  

this code ''852F-EF00'' is your own code, why should I put it in my own device? please explain.

![image](https://github.com/wzshiming/gh-gpt/assets/12984941/ecc61c20-1c76-4718-92d3-3d5873dc1dd4)
![image](https://github.com/wzshiming/gh-gpt/assets/12984941/335d972b-c70b-46ca-a6cf-5e8c4fa37784)

As you can see, the command ./cmd/gh-gpt login does not work.  .\gh-gpt login  this one works but does not give any results.

Please let me know what is inside the exe file? What will happen if i open it?

**Comment by wzshiming** [comment]
oh. I got, you are not to build

you can run `go build ./cmd/gh-gpt` to generation gh-gpt.exe
or download https://github.com/wzshiming/gh-gpt/releases/download/v0.5.0/gh-gpt_windows_amd64.exe to gh-gpt.exe


and run `gh-gpt.exe login` to login

**Comment by thelege2nd** [comment]
Please explain how can I get the COPILOT_TOKEN. Thank you @wzshiming

**Comment by wzshiming** [comment]
https://github.com/wzshiming/gh-gpt?tab=readme-ov-file#login-copilot-in-ide

You can use JetBrains/VSCode to login copilot and get it on the path

or

use `gh-gpt login`

**Comment by wzshiming** [comment]
BTY I think you may be looking for https://github.com/xtekky/gpt4free

**Comment by thelege2nd** [comment]
thank you
