### ISSUE TITLE
is this working?

### ISSUE THREAD

**Issue by thelege2ndG** [wzshiming/gh-gpt#5]
hello, is this still working? can you please check and let me know?? i get this error.

`API Error: Status Code 403, {"code":403,"error":"{\"error_details\":{\"url\":\"[support.github.com?editor={EDITOR}...](https://support.github.com/?editor=%7BEDITOR%7D%5C%22,%5C%22message%5C%22:%5C%22Please) only use approved clients for Copilot. You are currently logged in as HIDDEN.\",\"title\":\"Copilot Unavailable\",\"notification_id\":\"go_http_client\"},\"message\":\"Resource not accessible by integration\"}"}`

**Comment by wzshiming** [comment]
Sorry, this is no longer maintained.
